site:
  about:
    siteName: "Leeds KUG"
    subtitle: "Leeds Kotlin User Group"
    siteDescription: "A Leeds based Kotlin User Group, run by Kotlin enthusiasts for people interested in learning more about Kotlin and the Kotlin Community! Check out our posts for upcoming events, or check us out on Twitter where we'll also post information about upcoming events."
    avatar: "assets/media/LeedsKotlinUserGroup.png"

theme:
  social:
    twitter: "LeedsKotlin"
    github: "Leeds-Kotlin-User-Group"
  menu:
    - type: "page"
      title: "Home"
      url: "/"
    - type: "pages"
      atRoot: true
  sidebar:
    - type: recentPosts
      limit: 3
      category: personal
      noWrapper: true
      template:
        - "includes/postPreview_list"
  extraCss:
    - "assets/css/extraCss.scss"
    - "assets/css/pygments.scss"
  extraJs:
    - "assets/js/extraJs.js"

services:
  generators:
    externalIndices:
      - "https://orchid.netlify.com/meta/all.index.json"
