site:
  about:
    siteName: 'Leeds KUG'
    subtitle: 'Leeds Kotlin User Group'
    siteDescription: "Kotlin, it`s like a less shit Java."
    avatar: 'assets/media/placeholder-logo.png'

theme:
  social:
    twitter: 'LeedsKotlin'
    github: 'Leeds-Kotlin-User-Group'
  menu:
    - type: 'page'
      title: 'Home'
      url: '/'
    - type: "pages"
      atRoot: true
  sidebar:
    - type: recentPosts
      limit: 3
      category: personal
      noWrapper: true
      template:
        - 'includes/postPreview_list'
  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'

services:
  generators:
    externalIndices:
      - 'https://orchid.netlify.com/meta/all.index.json'
