permalink: ':category/:year/:monthName/:slug'
categories:
  - key: 'welcome'
    title: 'Welcome to Leed Kotlin User Group'
  - key: 'category'
    title: 'Category 2'

authors:
  - name: 'LKUG'
    avatar: 'assets/media/avatar.jpg'
    email: 'email@domain.tld'
